{
 "title": "Moqui Dashboard",
 "tags": [ "moqui" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "moqui_info" } },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "moqui_info{namespace=~\"$namespace\"}"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "moqui_info{namespace=~\"$namespace\",job=~\"$job\"}"
    }
   },
   {
    "name": "postgres_instance",
    "label": "Postgres Instance",
    "query": {
     "query": "cnpg_pg_postmaster_start_time{namespace=~\"$namespace\"}"
    }
   },
   {
    "name": "metric_name",
    "label": "Hit Group",
    "query": {
     "query": "label_values(moqui_hits_seconds_count,metric_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod Restarts/OOM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods with OOM killed containers by last termination reason",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\", namespace=~\"$namespace\", pod =~\"$pod\", job =~ \"$job\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "delta(kube_pod_container_status_restarts_total{container=\"moqui\", namespace=~\"$namespace\", job =~ \"$job\", pod =~ \"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Throughput / Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Hit Count by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(moqui_hits_slowhits_total{namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", metric_name=~\"$metric_name\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} slow"
    },
    {
     "expr": "sum by(namespace) (rate(moqui_hits_errors_total{namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", metric_name=~\"$metric_name\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} error"
    },
    {
     "expr": "sum by(namespace) (rate(moqui_hits_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", metric_name=~\"$metric_name\"}[$__rate_interval])-rate(moqui_hits_slowhits_total{namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", metric_name=~\"$metric_name\"}[$__rate_interval])-rate(moqui_hits_errors_total{namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", metric_name=~\"$metric_name\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} normal"
    }
   ]
  },
  {
   "title": "Hit Time by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(namespace) (rate(moqui_hits_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\", metric_name=~\"$metric_name\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Hit Latency (Average Percentiles)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(moqui_hits_seconds_bucket{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", metric_name=~\"$metric_name\"}[$__rate_interval])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(moqui_hits_seconds_bucket{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", metric_name=~\"$metric_name\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(moqui_hits_seconds_bucket{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", metric_name=~\"$metric_name\"}[$__rate_interval])))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(moqui_hits_seconds_bucket{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", metric_name=~\"$metric_name\"}[$__rate_interval])))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(moqui_hits_seconds_bucket{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", metric_name=~\"$metric_name\", metric_name=~\"$metric_name\"}[$__rate_interval])))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Hit Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(le) (rate(moqui_hits_seconds_bucket{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", metric_name=~\"$metric_name\"}[$__rate_interval]))*60",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Thread count avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "avg by(namespace) (moqui_jvm_thread_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"})",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(namespace) (irate(container_network_receive_bytes_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "IO Read total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(namespace) (rate(container_fs_reads_bytes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "IO Write total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(namespace) (rate(container_fs_writes_bytes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  { "title": "Worker Pools and Service Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Scheduled Jobs Worker Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "avg(moqui_scheduledpool_active{namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(moqui_jobrunner_jobs_running{namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(moqui_jobrunner_slots{namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"})",
     "legendFormat": "Slots"
    }
   ]
  },
  {
   "title": "Job Runner",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "avg(delta(moqui_jobrunner_execute_total{namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[10m])) / 10",
     "legendFormat": "Job Run Eval"
    },
    {
     "expr": "avg(increase(moqui_jobrunner_run_total{namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[1m]))",
     "legendFormat": "Job Runs"
    }
   ]
  },
  {
   "title": "Worker Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "avg(moqui_workerpool_current{namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"})",
     "legendFormat": "Pool"
    },
    {
     "expr": "avg(moqui_workerpool_max_size{namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"})",
     "legendFormat": "Pool Max"
    },
    {
     "expr": "avg(moqui_workerpool_active{namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"})",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postgres Clusters",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(cnpg_collector_up{namespace=~\"$namespace\"}) by (cluster, namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Filesystems",
     "type": "table",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$postgres_instance\"})"
      },
      {
       "expr": "sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$postgres_instance\"})"
      },
      {
       "expr": "(sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$postgres_instance\"})) - (sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$postgres_instance\"}))",
       "legendFormat": "__auto"
      },
      {
       "expr": "kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$postgres_instance\"}",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "(\n  (sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$postgres_instance\"})) - (sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$postgres_instance\"}))\n  ) / (\n    sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$postgres_instance\"})\n    )",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$postgres_instance\"})) - (sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$postgres_instance\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM & OpenSearch Info",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "moqui_info{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "moqui_elasticsearch_server_info{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Artifact Versions for ${pod}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "repeat": "pod",
   "collapsed": true,
   "panels": [
    {
     "title": "Artifact versions",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "moqui_artifact_detail{namespace=~\"$namespace\", pod=\"$pod\", artifact_name!=\"tools\", artifact_name!=\"webroot\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Garbage Collection Count per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "increase(moqui_memory_gc_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Garbage Collection Time per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(moqui_memory_gc_time_seconds{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Heap Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(moqui_memory_heap_usage_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Non-Heap Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(moqui_memory_nonheap_usage_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Heap Available",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "moqui_memory_heap_max_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}-moqui_memory_heap_usage_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Heap Available %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(moqui_memory_heap_max_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}-moqui_memory_heap_usage_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"})/moqui_memory_heap_max_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Moqui Total Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "moqui_memory_heap_committed_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}+moqui_memory_nonheap_committed_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(pod) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", container!=\"\", image!=\"\", pod=~\"$pod\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$postgres_instance\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Blocked Queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
     "targets": [
      {
       "expr": "cnpg_backends_waiting_total{namespace=~\"$namespace\",pod=~\"$postgres_instance\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$postgres_instance\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$postgres_instance\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "IO Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=~\"$namespace\", job=~\"$job\", pod=~\"$postgres_instance\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "IO Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=~\"$namespace\", job=~\"$job\", pod=~\"$postgres_instance\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "DB Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "cnpg_pg_database_size_bytes{datname!~\"template.*\",datname!=\"postgres\",namespace=~\"$namespace\",pod=~\"$postgres_instance\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Filesystem Available %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$postgres_instance\"})\n) / sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$postgres_instance\"})\n",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  }
 ]
}